name: Deploy Vite App

on:
  push:
    branches:
      - main  # Change if using a different branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build Vite App
        run: npm run build
        env:
          VITE_DETRACK_API_KEY: ${{ secrets.VITE_DETRACK_API_KEY }}
          VITE_ORCA_API_KEY: ${{ secrets.VITE_ORCA_API_KEY }}
          VITE_DETRACK_SERVICE: ${{ env.VITE_DETRACK_SERVICE }}
          VITE_ORCA_SERVICE: ${{ env.VITE_ORCA_SERVICE }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
